#:import CardWidgetTurn app.common.customWidgets.cardWidgetTurn
<CardWidgetTurn>:
    id:card
    line_color:(0.2, 0.2, 0.2, 0.8)
    style:"elevated"
    name:''
    size_hint_y:None
    BoxLayout:
        orientation:'horizontal'
        padding:dp(8)
s
        MDLabel:
            id:label_name
            halign: "center"
            text: root.name
            bold: True
            font_size:dp(24)

